-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "django_migrations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_migrations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"app" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"applied" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "django_content_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_content_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"app_label" varchar(100) NOT NULL,
	"model" varchar(100) NOT NULL,
	CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE("app_label","model")
);
--> statement-breakpoint
CREATE TABLE "auth_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"content_type_id" integer NOT NULL,
	"codename" varchar(100) NOT NULL,
	CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE("content_type_id","codename")
);
--> statement-breakpoint
CREATE TABLE "auth_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(150) NOT NULL,
	CONSTRAINT "auth_group_name_key" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "auth_group_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_group_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"group_id" integer NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE("group_id","permission_id")
);
--> statement-breakpoint
CREATE TABLE "auth_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"password" varchar(128) NOT NULL,
	"last_login" timestamp with time zone,
	"is_superuser" boolean NOT NULL,
	"username" varchar(150) NOT NULL,
	"first_name" varchar(150) NOT NULL,
	"last_name" varchar(150) NOT NULL,
	"email" varchar(254) NOT NULL,
	"is_staff" boolean NOT NULL,
	"is_active" boolean NOT NULL,
	"date_joined" timestamp with time zone NOT NULL,
	CONSTRAINT "auth_user_username_key" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "auth_user_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_user_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"group_id" integer NOT NULL,
	CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE("user_id","group_id")
);
--> statement-breakpoint
CREATE TABLE "auth_user_user_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_user_user_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE("user_id","permission_id")
);
--> statement-breakpoint
CREATE TABLE "django_admin_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_admin_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"action_time" timestamp with time zone NOT NULL,
	"object_id" text,
	"object_repr" varchar(200) NOT NULL,
	"action_flag" smallint NOT NULL,
	"change_message" text NOT NULL,
	"content_type_id" integer,
	"user_id" integer NOT NULL,
	CONSTRAINT "django_admin_log_action_flag_check" CHECK (action_flag >= 0)
);
--> statement-breakpoint
CREATE TABLE "store" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "store_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"code" varchar(255) NOT NULL,
	"platform" varchar(20) NOT NULL,
	"url" varchar(200) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "store_name_key" UNIQUE("name"),
	CONSTRAINT "store_code_key" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "chatbot_widget_customization" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chatbot_widget_customization_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"primary_color" varchar(7),
	"secondary_color" varchar(7),
	"tertiary_color" varchar(7),
	"logo" varchar(255),
	"welcome_message" varchar(500) NOT NULL,
	"greeting_message" varchar(500) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"store_id" bigint NOT NULL,
	CONSTRAINT "chatbot_widget_customization_store_id_key" UNIQUE("store_id")
);
--> statement-breakpoint
CREATE TABLE "chatbot_widget_customization_quick_actions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chatbot_widget_customization_quick_actions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"chatbotwidgetcustomization_id" bigint NOT NULL,
	"quickaction_id" bigint NOT NULL,
	CONSTRAINT "chatbot_widget_customiza_chatbotwidgetcustomizati_56a32df7_uniq" UNIQUE("chatbotwidgetcustomization_id","quickaction_id")
);
--> statement-breakpoint
CREATE TABLE "quick_action" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quick_action_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"message" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "quick_link" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quick_link_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"url" varchar(200) NOT NULL,
	"priority" integer,
	"is_active" boolean NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"widget_id" bigint NOT NULL,
	CONSTRAINT "quick_link_priority_check" CHECK (priority >= 0)
);
--> statement-breakpoint
CREATE TABLE "store_credentials" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "store_credentials_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"base_url" varchar(200) NOT NULL,
	"storefront_token" text,
	"admin_access_token" text,
	"mcp_url" varchar(200),
	"n8n_url" varchar(200),
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"store_id" bigint NOT NULL,
	CONSTRAINT "store_credentials_store_id_key" UNIQUE("store_id")
);
--> statement-breakpoint
CREATE TABLE "store_faqs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "store_faqs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"question" text NOT NULL,
	"answer" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"store_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "otp_store" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "otp_store_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"thread_id" varchar(150),
	"email" varchar(254) NOT NULL,
	"otp" varchar(6) NOT NULL,
	"is_verified" boolean NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chat_customer" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat_customer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"first_name" varchar(100) NOT NULL,
	"last_name" varchar(100) NOT NULL,
	"email" varchar(254) NOT NULL,
	"store" varchar(255),
	"customer_id" varchar(50) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chat_address" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat_address_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"street" jsonb,
	"country_id" varchar(3),
	"region" varchar(100),
	"city" varchar(100),
	"postcode" varchar(20),
	"telephone" varchar(20),
	"default_billing" boolean NOT NULL,
	"default_shipping" boolean NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"customer_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chat_thread" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"is_active" boolean NOT NULL,
	"followup_level" integer NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"ended_at" timestamp with time zone,
	"updated_at" timestamp with time zone NOT NULL,
	"customer_id" bigint,
	"store_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chatbot_feedback" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chatbot_feedback_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"rating" varchar(10) NOT NULL,
	"feedback_message" varchar(500),
	"conversation_summary" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"chat_message_id" bigint,
	"thread_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chat_botevent" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat_botevent_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"event_type" varchar(50) NOT NULL,
	"product_id" varchar(100),
	"product_name" varchar(255),
	"category" varchar(255),
	"created_at" timestamp with time zone NOT NULL,
	"thread_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chat_history" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"role" varchar(20) NOT NULL,
	"json_content" jsonb NOT NULL,
	"message_type" varchar(30) NOT NULL,
	"response_time" double precision NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"thread_id" uuid NOT NULL,
	"workflow" varchar(30),
	"message" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai_insights" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai_insights_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"underperforming_cases" jsonb NOT NULL,
	"overperforming_cases" jsonb NOT NULL,
	"resolution_success_rate" numeric(5, 2) NOT NULL,
	"reason_for_score" text NOT NULL,
	"tags" jsonb NOT NULL,
	"ai_insight_required" boolean NOT NULL,
	"next_actionable_items" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"thread_id" uuid NOT NULL,
	CONSTRAINT "ai_insights_thread_id_key" UNIQUE("thread_id")
);
--> statement-breakpoint
CREATE TABLE "sentiment_analysis" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sentiment_analysis_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"total_queries" integer NOT NULL,
	"resolved_queries" integer NOT NULL,
	"unresolved_queries" integer NOT NULL,
	"resolved_queries_list" jsonb NOT NULL,
	"unresolved_queries_list" jsonb NOT NULL,
	"top_intent" varchar(50) NOT NULL,
	"search_keywords" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"thread_id" uuid NOT NULL,
	CONSTRAINT "sentiment_analysis_thread_id_key" UNIQUE("thread_id")
);
--> statement-breakpoint
CREATE TABLE "session_resolution_verdict" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_resolution_verdict_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"verdict" varchar(20) NOT NULL,
	"reason" text,
	"confidence" double precision NOT NULL,
	"total_queries" integer NOT NULL,
	"resolved_count" integer NOT NULL,
	"unresolved_count" integer NOT NULL,
	"query_summaries" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"store_id" bigint,
	"thread_id" uuid NOT NULL,
	CONSTRAINT "session_resolution_verdict_thread_id_key" UNIQUE("thread_id")
);
--> statement-breakpoint
CREATE TABLE "user_metadata" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_metadata_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"customer_name" varchar(255),
	"geo_location" varchar(255),
	"ip_address" "inet",
	"device_type" varchar(100),
	"browser" varchar(100),
	"os" varchar(100),
	"initial_cart_data" jsonb NOT NULL,
	"updated_cart_data" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"thread_id" uuid NOT NULL,
	CONSTRAINT "user_metadata_thread_id_key" UNIQUE("thread_id")
);
--> statement-breakpoint
CREATE TABLE "support_ticket" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "support_ticket_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"platform" varchar(30) NOT NULL,
	"ticket_id" bigint NOT NULL,
	"status" varchar(20) NOT NULL,
	"subject" varchar(500) NOT NULL,
	"description" text NOT NULL,
	"requester_id" bigint,
	"email_config_id" bigint,
	"platform_created_at" timestamp with time zone,
	"platform_updated_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"customer_id" bigint,
	"store_id" bigint NOT NULL,
	"thread_id" uuid NOT NULL,
	CONSTRAINT "support_ticket_ticket_id_key" UNIQUE("ticket_id")
);
--> statement-breakpoint
CREATE TABLE "_scrapeLinkslinks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""_scrapeLinkslinks_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"link_type" varchar NOT NULL,
	"url" varchar(200) NOT NULL,
	"status" varchar(20) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"store_id" bigint
);
--> statement-breakpoint
CREATE TABLE "knowledge_storelibrarydocument" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "knowledge_storelibrarydocument_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"type" varchar(100) NOT NULL,
	"size" bigint NOT NULL,
	"status" varchar(255) NOT NULL,
	"path" varchar(255) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"store_id" bigint NOT NULL,
	CONSTRAINT "knowledge_storelibrarydocument_size_check" CHECK (size >= 0)
);
--> statement-breakpoint
CREATE TABLE "django_session" (
	"session_key" varchar(40) PRIMARY KEY NOT NULL,
	"session_data" text NOT NULL,
	"expire_date" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chatbot_widget_customization" ADD CONSTRAINT "chatbot_widget_customization_store_id_c92a0380_fk_store_id" FOREIGN KEY ("store_id") REFERENCES "public"."store"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chatbot_widget_customization_quick_actions" ADD CONSTRAINT "chatbot_widget_custo_chatbotwidgetcustomi_dbdfee1b_fk_chatbot_w" FOREIGN KEY ("chatbotwidgetcustomization_id") REFERENCES "public"."chatbot_widget_customization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chatbot_widget_customization_quick_actions" ADD CONSTRAINT "chatbot_widget_custo_quickaction_id_41680d88_fk_quick_act" FOREIGN KEY ("quickaction_id") REFERENCES "public"."quick_action"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quick_link" ADD CONSTRAINT "quick_link_widget_id_7a6f5641_fk_chatbot_w" FOREIGN KEY ("widget_id") REFERENCES "public"."chatbot_widget_customization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_credentials" ADD CONSTRAINT "store_credentials_store_id_3c6945c8_fk_store_id" FOREIGN KEY ("store_id") REFERENCES "public"."store"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_faqs" ADD CONSTRAINT "store_faqs_store_id_77dc29ac_fk_store_id" FOREIGN KEY ("store_id") REFERENCES "public"."store"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_address" ADD CONSTRAINT "chat_address_customer_id_f707e8c0_fk_chat_customer_id" FOREIGN KEY ("customer_id") REFERENCES "public"."chat_customer"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_thread" ADD CONSTRAINT "chat_thread_customer_id_31f2879e_fk_chat_customer_id" FOREIGN KEY ("customer_id") REFERENCES "public"."chat_customer"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_thread" ADD CONSTRAINT "chat_thread_store_id_b856f451_fk_store_id" FOREIGN KEY ("store_id") REFERENCES "public"."store"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chatbot_feedback" ADD CONSTRAINT "chatbot_feedback_chat_message_id_253617b0_fk_chat_history_id" FOREIGN KEY ("chat_message_id") REFERENCES "public"."chat_history"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chatbot_feedback" ADD CONSTRAINT "chatbot_feedback_thread_id_e45b9eb9_fk_chat_thread_id" FOREIGN KEY ("thread_id") REFERENCES "public"."chat_thread"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_botevent" ADD CONSTRAINT "chat_botevent_thread_id_aad111f3_fk_chat_thread_id" FOREIGN KEY ("thread_id") REFERENCES "public"."chat_thread"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_history" ADD CONSTRAINT "chat_history_thread_id_4bac8b19_fk_chat_thread_id" FOREIGN KEY ("thread_id") REFERENCES "public"."chat_thread"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_insights" ADD CONSTRAINT "ai_insights_thread_id_ff0c2d42_fk_chat_thread_id" FOREIGN KEY ("thread_id") REFERENCES "public"."chat_thread"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sentiment_analysis" ADD CONSTRAINT "sentiment_analysis_thread_id_ad847984_fk_chat_thread_id" FOREIGN KEY ("thread_id") REFERENCES "public"."chat_thread"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_resolution_verdict" ADD CONSTRAINT "session_resolution_verdict_store_id_d0e896c1_fk_store_id" FOREIGN KEY ("store_id") REFERENCES "public"."store"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_resolution_verdict" ADD CONSTRAINT "session_resolution_verdict_thread_id_72042b2d_fk_chat_thread_id" FOREIGN KEY ("thread_id") REFERENCES "public"."chat_thread"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_metadata" ADD CONSTRAINT "user_metadata_thread_id_368d9e3f_fk_chat_thread_id" FOREIGN KEY ("thread_id") REFERENCES "public"."chat_thread"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "support_ticket" ADD CONSTRAINT "support_ticket_customer_id_21b0e471_fk_chat_customer_id" FOREIGN KEY ("customer_id") REFERENCES "public"."chat_customer"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "support_ticket" ADD CONSTRAINT "support_ticket_store_id_e4602dd4_fk_store_id" FOREIGN KEY ("store_id") REFERENCES "public"."store"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "support_ticket" ADD CONSTRAINT "support_ticket_thread_id_2978cb77_fk_chat_thread_id" FOREIGN KEY ("thread_id") REFERENCES "public"."chat_thread"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "_scrapeLinkslinks" ADD CONSTRAINT "_scrapeLinkslinks_store_id_8ce11e9b_fk_store_id" FOREIGN KEY ("store_id") REFERENCES "public"."store"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "knowledge_storelibrarydocument" ADD CONSTRAINT "knowledge_storelibrarydocument_store_id_032910f7_fk_store_id" FOREIGN KEY ("store_id") REFERENCES "public"."store"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" USING btree ("content_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" USING btree ("name" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" USING btree ("group_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" USING btree ("permission_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_user_username_6821ab7c_like" ON "auth_user" USING btree ("username" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" USING btree ("group_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" USING btree ("user_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" USING btree ("permission_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" USING btree ("user_id" int4_ops);--> statement-breakpoint
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" USING btree ("content_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" USING btree ("user_id" int4_ops);--> statement-breakpoint
CREATE INDEX "store_code_5512d74c_like" ON "store" USING btree ("code" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "store_name_fb31a80d_like" ON "store" USING btree ("name" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "chatbot_widget_customizati_chatbotwidgetcustomization_dbdfee1b" ON "chatbot_widget_customization_quick_actions" USING btree ("chatbotwidgetcustomization_id" int8_ops);--> statement-breakpoint
CREATE INDEX "chatbot_widget_customizati_quickaction_id_41680d88" ON "chatbot_widget_customization_quick_actions" USING btree ("quickaction_id" int8_ops);--> statement-breakpoint
CREATE INDEX "quick_link_widget_id_7a6f5641" ON "quick_link" USING btree ("widget_id" int8_ops);--> statement-breakpoint
CREATE INDEX "store_faqs_store_id_77dc29ac" ON "store_faqs" USING btree ("store_id" int8_ops);--> statement-breakpoint
CREATE INDEX "chat_address_customer_id_f707e8c0" ON "chat_address" USING btree ("customer_id" int8_ops);--> statement-breakpoint
CREATE INDEX "chat_thread_customer_id_31f2879e" ON "chat_thread" USING btree ("customer_id" int8_ops);--> statement-breakpoint
CREATE INDEX "chat_thread_store_id_b856f451" ON "chat_thread" USING btree ("store_id" int8_ops);--> statement-breakpoint
CREATE INDEX "chatbot_fee_thread__ce8e5f_idx" ON "chatbot_feedback" USING btree ("thread_id" uuid_ops,"created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "chatbot_feedback_chat_message_id_253617b0" ON "chatbot_feedback" USING btree ("chat_message_id" int8_ops);--> statement-breakpoint
CREATE INDEX "chatbot_feedback_thread_id_e45b9eb9" ON "chatbot_feedback" USING btree ("thread_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "chat_botevent_thread_id_aad111f3" ON "chat_botevent" USING btree ("thread_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "chat_histor_created_2850f7_idx" ON "chat_history" USING btree ("created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "chat_histor_message_aee83b_idx" ON "chat_history" USING btree ("message_type" text_ops);--> statement-breakpoint
CREATE INDEX "chat_histor_role_2d2777_idx" ON "chat_history" USING btree ("role" text_ops);--> statement-breakpoint
CREATE INDEX "chat_histor_thread__381e32_idx" ON "chat_history" USING btree ("thread_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "chat_history_thread_id_4bac8b19" ON "chat_history" USING btree ("thread_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "session_resolution_verdict_store_id_d0e896c1" ON "session_resolution_verdict" USING btree ("store_id" int8_ops);--> statement-breakpoint
CREATE INDEX "support_tic_custome_b1ab40_idx" ON "support_ticket" USING btree ("customer_id" int8_ops);--> statement-breakpoint
CREATE INDEX "support_tic_platfor_507db3_idx" ON "support_ticket" USING btree ("platform" text_ops);--> statement-breakpoint
CREATE INDEX "support_tic_status_363e60_idx" ON "support_ticket" USING btree ("status" text_ops);--> statement-breakpoint
CREATE INDEX "support_tic_store_i_9bc370_idx" ON "support_ticket" USING btree ("store_id" int8_ops);--> statement-breakpoint
CREATE INDEX "support_tic_thread__d6c413_idx" ON "support_ticket" USING btree ("thread_id" uuid_ops,"created_at" uuid_ops);--> statement-breakpoint
CREATE INDEX "support_tic_ticket__1d6a0f_idx" ON "support_ticket" USING btree ("ticket_id" int8_ops);--> statement-breakpoint
CREATE INDEX "support_ticket_customer_id_21b0e471" ON "support_ticket" USING btree ("customer_id" int8_ops);--> statement-breakpoint
CREATE INDEX "support_ticket_store_id_e4602dd4" ON "support_ticket" USING btree ("store_id" int8_ops);--> statement-breakpoint
CREATE INDEX "support_ticket_thread_id_2978cb77" ON "support_ticket" USING btree ("thread_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "_scrapeLinkslinks_store_id_8ce11e9b" ON "_scrapeLinkslinks" USING btree ("store_id" int8_ops);--> statement-breakpoint
CREATE INDEX "knowledge_storelibrarydocument_store_id_032910f7" ON "knowledge_storelibrarydocument" USING btree ("store_id" int8_ops);--> statement-breakpoint
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" USING btree ("expire_date" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" USING btree ("session_key" varchar_pattern_ops);
*/